-- 1) 더미 유저 생성
INSERT INTO users (kakao_id, email, nick_name, role, created_at, updated_at)
VALUES (999999, 'dummy@test.com', '더미유저', 'USER', NOW(), NOW());

-- 2) 더미 유저 ID 조회
SET @dummy_user_id = (SELECT id FROM users WHERE email = 'dummy@test.com' LIMIT 1);

-- 3) 임시 숫자 테이블 생성
DROP TABLE IF EXISTS temp_numbers;

CREATE TABLE temp_numbers (
                              n INT PRIMARY KEY
);

-- 4) 5만 개 숫자 채우기
INSERT INTO temp_numbers (n)
SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 + 1
FROM
    (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
    (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
    (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
    (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
    (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
WHERE a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 < 50000;

-- 5) 게시글 5만개 Insert
INSERT INTO posts (title, content, user_id, created_at, updated_at)
SELECT
    CONCAT('더미 제목 ', n),
    CONCAT('더미 내용 ', n),
    @dummy_user_id,
    NOW(),
    NOW()
FROM temp_numbers;

-- 6) 임시 테이블 삭제
DROP TABLE temp_numbers;
